import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
//-----------------------------
// import { redirect } from 'next/navigation';
// import { cookies } from 'next/headers';
import { NextAuthProvider } from "./providers";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  // title: "Create Next App",
  // description: "Generated by create next app",
  title: "Employee Management System",
  description: "A system to manage employees using Next.js and Google Sheets",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      > */}
      <body className={inter.className}>

        {/* ส่วนของ Header  */}


        {/* ส่วนของ เนื้อหา */}
        <NextAuthProvider>
          {children}
        </NextAuthProvider>

        {/* ส่วนของ Footer */}

      </body>
    </html>
  );
}
